sudo: required

language: bash

services:
- docker

script:

  # Update docker for multi-stage build
  # - sudo service docker stop
  # - curl -fsSL https://get.docker.com/ | sudo sh

  # Build all images
  - docker build --build-arg PLATFORM=linux-amd64 -t acrelle/discord-irc:linux-amd64 -f Dockerfile .
  
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.11.1/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
  
  - docker build --build-arg PLATFORM=linux-arm -t acrelle/discord-irc:linux-arm -f linux-arm32v7.Dockerfile .

  - >

    if [ -n "$TRAVIS_BUILD_NUMBER" ]; then
      # Push all images
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker push acrelle/discord-irc:linux-amd64
      docker push acrelle/discord-irc:linux-arm

      # Download manifest-tool
      wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64
      mv manifest-tool-linux-amd64 manifest-tool
      chmod +x manifest-tool
      # Push manifest-list
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template "acrelle/discord-irc:OS-ARCH" --target "acrelle/discord-irc:$TRAVIS_BUILD_NUMBER"
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template "acrelle/discord-irc:OS-ARCH" --target "acrelle/discord-irc:latest"
    fi