version: "2"

services:
  discord-irc:
    build: .
    image: acrelle/discord-irc
    container_name: discord-irc
    restart: unless-stopped
    volumes:
      - ~/appdata/discord-irc:/opt/discord-irc
